Vagrant.require_version ">= 1.4.3"
VAGRANTFILE_API_VERSION = "2"

BOX='centos7-standard'
BOX_URL='https://www.dropbox.com/s/hiarmp3cdzjy94o/centos7-standard.box?dl=1'

BOX_OPENSTACK='openstack'
BOX_URL_OPENSTACK='https://www.dropbox.com/s/azww4ud3ti910os/openstack.box?dl=1'


os_host= 'os-node1'
client_host= 'client-node1'

rgw_node1_hostname= 'rgw-node1.cephcookbook.com'
rgw_node1_machine_name= 'rgw-node1'

us_east_rgw_hostname= 'us-east-1.cephcookbook.com'
us_east_rgw_machine_name= 'us-east-1'

us_west_rgw_hostname= 'us-west-1.cephcookbook.com'
us_west_rgw_machine_name= 'us-west-1'

oc_hostname= 'owncloud.cephcookbook.com'
oc_name= 'owncloud'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
                if (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
                   config.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=700,fmode=600"]
                else
                   config.vm.synced_folder ".", "/vagrant"
                end
                if Vagrant.has_plugin?("vagrant-cachier")
                   config.cache.scope = :box
                end
                if Vagrant.has_plugin?("vagrant-vbguest")
                   config.vbguest.auto_update = false
                   config.vbguest.no_install = true
                   config.vbguest.no_remote = true
                end
                (1..8).each do |i|
                   config.vm.define "ceph-node#{i}" do |d|
                        d.vm.box = "bento/centos-7.6" 
                        # d.vm.box = BOX
                        # d.vm.box_url = BOX_URL
                        if (i > 4)
                                d.vm.network "private_network", ip: "192.16.1.11#{i}"
                        else
                                d.vm.network "private_network", ip: "192.16.1.10#{i}"
                        end
                        d.vm.hostname = "ceph-node#{i}"                        
			d.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
                        d.vm.provision "shell", path: "post-deploy.sh",run: "always"
                        d.vm.provider "virtualbox" do |v|
                                v.customize ["modifyvm", :id, "--memory", "750"]
                                v.name = "ceph-node#{i}"
                                #v.gui = true
                                fileName2 =  "ceph-node#{i}/ceph-node#{i}_disk2.vdi"
                                fileName3 =  "ceph-node#{i}/ceph-node#{i}_disk3.vdi"
                                fileName4 =  "ceph-node#{i}/ceph-node#{i}_disk4.vdi"
                                unless File.exist?(fileName2)
                                v.customize ['createhd', '--filename', fileName2,'--size', 1 * 20480]
                                v.customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', fileName2]
                                end

                                unless File.exist?(fileName3)
                                v.customize ['createhd', '--filename', fileName3,'--size', 1 * 20480]
                                v.customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', fileName3]
                                end

                                unless File.exist?(fileName4)
                                v.customize ['createhd', '--filename', fileName4,'--size', 1 * 20480]
                                v.customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', 3, '--device', 0, '--type', 'hdd', '--medium', fileName4]
                                end
                        end
                    end
                end
##################################### Configuration for OpenStack node #####################################################

                 config.vm.define :"openstack-node1" do |os|
                        os.vm.box = BOX_OPENSTACK
                        os.vm.box_url = BOX_URL_OPENSTACK
                        os.vm.network :private_network, ip: "192.16.1.111"
                        os.vm.hostname = os_host
                        os.vm.synced_folder ".", "/vagrant", disabled: true
			os.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
                        os.vm.provision "shell", path: "post-deploy.sh",run: "always"
                        os.vm.provider "virtualbox" do |v|

                                v.customize ["modifyvm", :id, "--memory", "4096"]
                                v.name = os_host
                                v.gui = true

                        end
                  end

##################################### Configuration for client node #####################################################

                 config.vm.define :"client-node1" do |os|
                        os.vm.box = BOX
                        os.vm.box_url = BOX_URL
                        os.vm.network :private_network, ip: "192.16.1.110"
                        os.vm.hostname = client_host
                        os.vm.synced_folder ".", "/vagrant", disabled: true
			os.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
			os.vm.provision "shell", path: "post-deploy.sh"
                        os.vm.provider "virtualbox" do |v|

                                v.customize ["modifyvm", :id, "--memory", "512"]
                                v.name = client_host
                                v.gui = true

                        end
                  end

##################################### Configuration for rgw-node1 #####################################################

                 config.vm.define :"rgw-node1" do |rgw|
                        rgw.vm.box = BOX
                        rgw.vm.box_url = BOX_URL
                        rgw.vm.network :private_network, ip: "192.16.1.106"
                        rgw.vm.hostname = rgw_node1_hostname
                        rgw.vm.synced_folder ".", "/vagrant", disabled: true
                        rgw.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
                        rgw.vm.provision "shell", path: "post-deploy.sh",run: "always"
                        rgw.vm.provider "virtualbox" do |v|

                                v.customize ["modifyvm", :id, "--memory", "512"]
                                v.name = rgw_node1_machine_name
                                v.gui = true

                        end
                  end

##################################### Configuration for us-east-1 Rados Gateway Node #######################################

                 config.vm.define :"us-east-1" do |use1|
                        use1.vm.box = BOX
                        use1.vm.box_url = BOX_URL
                        use1.vm.network :private_network, ip: "192.16.1.107"
                        use1.vm.hostname = us_east_rgw_hostname 
                        use1.vm.synced_folder ".", "/vagrant", disabled: true
                        use1.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
                        use1.vm.provision "shell", path: "post-deploy.sh",run: "always"
                        use1.vm.provider "virtualbox" do |v|

                                v.customize ["modifyvm", :id, "--memory", "512"]
                                v.name = us_east_rgw_machine_name 
                                v.gui = true

                        end
                  end

##################################### Configuration for us-west-1 Rados Gateway Node #######################################

                 config.vm.define :"us-west-1" do |usw1|
                        usw1.vm.box = BOX
                        usw1.vm.box_url = BOX_URL
                        usw1.vm.network :private_network, ip: "192.16.1.108"
                        usw1.vm.hostname = us_west_rgw_hostname
                        usw1.vm.synced_folder ".", "/vagrant", disabled: true
                        usw1.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
                        usw1.vm.provision "shell", path: "post-deploy.sh",run: "always"
                        usw1.vm.provider "virtualbox" do |v|

                                v.customize ["modifyvm", :id, "--memory", "512"]
                                v.name = us_west_rgw_machine_name
                                v.gui = true

                        end
                  end

##################################### Configuration for owncloud Node #######################################

                 config.vm.define :"owncloud" do |oc|
                        oc.vm.box = BOX
                        oc.vm.box_url = BOX_URL
                        oc.vm.network :private_network, ip: "192.16.1.120"
                        oc.vm.hostname = oc_hostname
                        oc.vm.synced_folder ".", "/vagrant", disabled: true
                        oc.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
                        oc.vm.provision "shell", path: "post-deploy.sh",run: "always"
                        oc.vm.provider "virtualbox" do |v|

                                v.customize ["modifyvm", :id, "--memory", "512"]
                                v.name = oc_name
                                v.gui = true

                        end
                  end
###############################################################################################################
end
